### ISSUE TITLE
make the reflection search/filtering functional

### ISSUE THREAD

**Issue by Hannah-Sofie** [Hannah-Sofie/SustainabilityDiary#20]
![Skjermbilde 2024-05-02 kl  23 47 26](https://github.com/Hannah-Sofie/SustainabilityDiary/assets/90150033/4ed1ac79-b861-415b-8e18-9f87fb44527d)

**Comment by Hannah-Sofie** [comment]
Examples/ideas for search/filtering:

1. Date Created:
- Newest First: Sort by the latest created entries.
- Oldest First: Sort by the earliest created entries.

2. Date Last Updated:
- Most Recently Updated: Useful for quickly finding recent changes.
- Least Recently Updated: Track older, untouched reflections.

3. Title:
- Alphabetical Order: Sorting by title A-Z or Z-A makes it easy to find by name.

4. Classroom:
- Filter by Classroom: Display only reflections belonging to specific classrooms, especially useful for teachers managing multiple groups.

5. Privacy:
- Public vs. Private: Separate personal reflections from those shared with others.

6. Search Text:
- Title or Content: A flexible text search across titles, content, or keywords makes it easier to find relevant reflections.

7. Tags or Labels:
- By Tags: If reflections have tags/labels (e.g., "Research," "Personal"), filtering by these allows for topic-based browsing.

**Comment by Jonhels** [comment]
Working on search and filter functionality, currently having some issues with connection from the frontend to the backend. Might be the middleware that is trying to filter the reflection input on edit.

**Comment by Jonhels** [comment]
Reflection search on entries now finished.

Reflection search component and reflection entries component now is a combined component that handles the search and showcase of entries since they were interconnected from the start. 

How it works: 
Search: 
- Newest First: Sorts the entries by creation date, with the newest entries appearing first.
- Oldest First: Sorts the entries by creation date, with the oldest entries appearing first.
- Most Recently Updated: Sorts the entries by their last update date, with the most recently updated entries appearing first.
- Least Recently Updated: Sorts the entries by their last update date, with the least recently updated entries appearing first.
- Title A-Z: Sorts the entries alphabetically by title in ascending order.
- Title Z-A: Sorts the entries alphabetically by title in descending order.

Entries: 
- Shows entries as it did before
- on click the modal openes 

Css:
- Separated css into two different css, one for entries and one for search
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Will close issue after successful merge to main

**Comment by Jonhels** [comment]
merged with no issues
